version: '3.1'
services:
  mongo_db:
    image: mongo
    restart: always
    env_file:
      - ./.env
    volumes:
      - mongo-volume:/data/db
    ports:
      - 27017:27017

volumes:
  mongo-volume: